// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg_AFir2FQVjjEM7HX-ZsDruwXlVuyQN0',
    appId: '1:837836535805:web:a164a7d61ba13639758b94',
    messagingSenderId: '837836535805',
    projectId: 'chat-app-ed136',
    authDomain: 'chat-app-ed136.firebaseapp.com',
    storageBucket: 'chat-app-ed136.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBztkTXptT71Nk6gktHHPNHSzpNi-jgY6U',
    appId: '1:837836535805:android:5878bce75d1d433b758b94',
    messagingSenderId: '837836535805',
    projectId: 'chat-app-ed136',
    storageBucket: 'chat-app-ed136.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBox9WGAmElI0oCXoQNL20kt1OF6SaUUfY',
    appId: '1:837836535805:ios:37bd1b6217f4666c758b94',
    messagingSenderId: '837836535805',
    projectId: 'chat-app-ed136',
    storageBucket: 'chat-app-ed136.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBox9WGAmElI0oCXoQNL20kt1OF6SaUUfY',
    appId: '1:837836535805:ios:a820bcb29d2210e8758b94',
    messagingSenderId: '837836535805',
    projectId: 'chat-app-ed136',
    storageBucket: 'chat-app-ed136.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
